[features]
seeds = false
skip-lint = false
[programs.devnet]
marketplace = "7ZGGMgd86tKJosUZfT3ohHeAGkH7cGaWGf9DYSaYcDJv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api-testnet.renec.foundation:8899"
wallet = ".wallet/master.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
