[features]
seeds = false
skip-lint = false
[programs.devnet]
solana = "8U2uMKTA35oa1tnQtrX7EfkbqXvNKjK8siAoX3wU9SVj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".wallet/master.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
