[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft = "GZe7acAQjBMqTpikfQGaxeYHmddoaK3Qdpqf2fU1XK6g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".wallet/master.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
