[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft = "B5rSEHZKKZqKUjb5KBLViv4TVS7U6acbENbC5RBKGJvJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".wallet/master.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
